SELECT 'ALTER SYSTEM KILL SESSION  ''' || S.SID || ',' || S.SERIAL# || ''' IMMEDIATE; '
FROM v$session S
INNER JOIN v$process P
ON S.PADDR = P.ADDR
WHERE S.STATUS = 'INACTIVE'
AND S.USERNAME NOT IN ('SYS', 'SYSMAN', 'DBSNMP')
AND S.LAST_CALL_ET > 0;
